/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

import "sst"
declare module "sst" {
  export interface Resource {
    "BucketLinkable": {
      "privateBucketName": string
      "publicBucketName": string
      "type": "sst.sst.Linkable"
    }
    "CLOUDFLARE_ACCESS_KEY_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLOUDFLARE_ACCOUNT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLOUDFLARE_SECRET_ACCESS_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Email": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "KelasTechWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
// cloudflare 
import * as cloudflare from "@cloudflare/workers-types";
declare module "sst" {
  export interface Resource {
    "PrivateBucket": cloudflare.R2Bucket
    "PublicBucket": cloudflare.R2Bucket
  }
}

import "sst"
export {}