/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

import "sst"
declare module "sst" {
  export interface Resource {
    "CfResources": {
      "accountId": string
      "dbId": string
      "type": "sst.sst.Linkable"
    }
    "CloudflareD1ApiToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "KelasTechWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
// cloudflare 
import * as cloudflare from "@cloudflare/workers-types";
declare module "sst" {
  export interface Resource {
    "KelasTechApi": cloudflare.Service
    "KelasTechDB": cloudflare.D1Database
  }
}

import "sst"
export {}